services:
  tree_house.keystone.user_provider.default:
    public: true
    class: TreeHouse\KeystoneBundle\Security\User\UserProvider
    arguments:
      - '@doctrine'
      - '%tree_house.keystone.model.user.class%'

  tree_house.keystone.token_authenticator:
    public: false
    class: TreeHouse\KeystoneBundle\Security\Authentication\TokenAuthenticator
    arguments:
      - '@tree_house.keystone.token_manager'
      - '@security.user_checker'

  tree_house.keystone.authentication.listener.http_post:
    public: false
    class: TreeHouse\KeystoneBundle\Security\Firewall\HttpPostAuthenticationListener
    arguments:
      - '@security.token_storage'
      - '@security.authentication.manager'
      - null # provider-shared key
      - '@logger'
    tags:
      - { name: monolog.logger, channel: security }

  tree_house.keystone.authentication.provider.http_post:
    public: false
    class: Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider
    arguments:
      - '@tree_house.keystone.user_provider'
      - '@security.user_checker'
      - null # provider-shared key
      - '@security.encoder_factory'

  tree_house.keystone.encoder.token:
    public: false
    class: TreeHouse\KeystoneBundle\Security\Encoder\TokenEncoder
    arguments:
      - '%secret%'

  tree_house.keystone.http.entry_point:
    public: false
    class: TreeHouse\KeystoneBundle\Security\Http\KeystoneEntryPoint
