services:
  tree_house.keystone.service_manager:
    public: true
    class: TreeHouse\KeystoneBundle\Manager\ServiceManager

  tree_house.keystone.token_manager:
    public: true
    class: TreeHouse\KeystoneBundle\Manager\TokenManager
    arguments:
      - '@tree_house.keystone.encoder.token'
      - '@doctrine'

  # definition for a Keystone service, used as a template in the extension
  tree_house.keystone.service:
    public: false
    class: TreeHouse\KeystoneBundle\Model\Service
    abstract: true
    arguments:
      - null # name
      - null # type
      - null # role
